import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/common-component/header";
import { ThemeProvider } from "@/components/ui/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`light ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="h-full w-full ">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
