import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`light ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="px-10 h-full w-full">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
